// Generated by CoffeeScript 1.9.2

/*
	文件相关
 */
var fileCtrl, fs;

fs = require('fs');

fileCtrl = {
  findDir: function(dir) {
    return files.forEach(function(n, i) {
      var stat;
      stat = fs.lstatSync(n);
      if (stat.isDirectory()) {
        return console.log(n);
      }
    });
  },
  isDir: function(dir) {
    var stat;
    dir = dir.replace(/\\/g, '//');
    if (fs.existsSync(dir)) {
      stat = fs.lstatSync(dir);
      if (stat.isDirectory()) {
        return true;
      } else {
        return false;
      }
    } else {
      return false;
    }
  },
  _json: [],
  saveHistory: function(dir) {
    var _flag, index, item, j, len, ref;
    dir = dir.replace(/\\/g, '//');
    _flag = false;
    ref = this._json;
    for (index = j = 0, len = ref.length; j < len; index = ++j) {
      item = ref[index];
      if (dir === item) {
        _flag = true;
      }
    }
    if (!_flag) {
      return this._json.push(dir);
    }
  }
};

module.exports = fileCtrl;
