// Generated by CoffeeScript 1.9.2
var _gitPath, cmd, fileCtrl, fileDrag, filePad;

fileCtrl = require('../_node/fileCtrl');

cmd = require('../_node/cmd');

_gitPath = 'D:\\Progra~1\\Git\\cmd\\git.exe';

fileDrag = $('#fileDrag');

window.ondragover = function(e) {
  e.preventDefault();
  return false;
};

window.ondrop = function(e) {
  e.preventDefault();
  return false;
};

fileDrag[0].ondragover = function(e) {
  e.preventDefault();
  return false;
};

fileDrag[0].ondrop = function(e) {
  var i, index, item, len, ref;
  ref = e.dataTransfer.files;
  for (index = i = 0, len = ref.length; i < len; index = ++i) {
    item = ref[index];
    if (fileCtrl.isDir(item.path)) {
      fileCtrl.saveHistory(item.path);
    }
  }
  filePad.append(fileCtrl._json);
  e.preventDefault();
  return false;
};

$('#gitPull').on('click', function() {
  var arr;
  arr = fileCtrl._json;
  return arr.forEach(function(item, index) {
    return cmd.exec(['cd ' + item, filePad.pullCmd], filePad.cmdCb);
  });
});

filePad = {
  append: function(arr) {
    var _html;
    _html = '';
    arr.forEach(function(item, index) {
      return _html = _html + ("<p>" + item + "</p>");
    });
    return fileDrag.html(_html);
  },
  cmdCb: function(error, stdout, stderr, str) {
    if (error) {
      throw error;
    } else {
      return $('#logPad').append(str + "<p>" + stdout + "</p>");
    }
  },
  pullCmd: _gitPath + ' pull'
};
